# -*- coding: utf-8 -*-
"""Evidence gate for replay prior qualification.

This tool is read-only and never enables or applies a prior. It converts the
diagnostics generated by PR #21 into explicit gates for a future experiment.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

VERSION = "V4.4-replay-qualification-gate"


def _utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _load_optional(path: str | Path) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    file_path = Path(path)
    if not file_path.exists():
        return None, {"available": False, "reason": "missing input", "path": str(file_path)}
    try:
        data = json.loads(file_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return None, {"available": False, "reason": f"invalid json: {exc}", "path": str(file_path)}
    if not isinstance(data, dict):
        return None, {"available": False, "reason": "input is not an object", "path": str(file_path)}
    return data, {"available": True, "path": str(file_path)}


def _replay_input(path: str) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    data, state = _load_optional(path)
    if not data:
        return data, state
    aggregate = data.get("aggregate") or {}
    calibration = aggregate.get("calibration_summary") or {}
    records = int(aggregate.get("records_count") or len(data.get("records") or []))
    leakage = int(aggregate.get("leakage_passed_count") or 0)
    state.update(
        {
            "records_replay": records,
            "leakage_passed_count": leakage,
            "prior_quality": calibration.get("prior_quality") or "unknown",
            "ranking_signal_quality": calibration.get("ranking_signal_quality") or "unknown",
        }
    )
    return data, state


def _benchmark_input(path: str) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    data, state = _load_optional(path)
    if not data:
        return data, state
    summary = data.get("benchmark_summary") or {}
    state.update(
        {
            "records_count": data.get("records_count") or 0,
            "signal_quality": summary.get("signal_quality") or "unknown",
            "recommendation": summary.get("recommendation") or "diagnostic_only",
        }
    )
    return data, state


def _diversity_input(path: str) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    data, state = _load_optional(path)
    if not data:
        return data, state
    state.update(
        {
            "diversity_gain": data.get("diversity_gain") or 0.0,
            "pool_source": data.get("pool_source") or "top_combinations",
            "unique_numbers_diversified": data.get("unique_numbers_diversified") or 0,
        }
    )
    return data, state


def _candidate_pool_input(path: str) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    data, state = _load_optional(path)
    if not data:
        return data, state
    state.update(
        {
            "best_available_pool": data.get("best_available_pool") or "none",
            "best_available_pool_size": data.get("best_available_pool_size") or 0,
            "can_improve_diversity_with_existing_data": bool(data.get("can_improve_diversity_with_existing_data")),
        }
    )
    return data, state


def _physics_input(path: str) -> tuple[dict[str, Any] | None, dict[str, Any]]:
    data, state = _load_optional(path)
    if not data:
        return data, state
    event = data.get("latest_event") or {}
    timing = data.get("regime_timing") or {}
    state.update(
        {
            "latest_event_suspected": bool(event.get("suspected")),
            "latest_event_status": event.get("status") or "unknown",
            "can_estimate_periodicity": bool(timing.get("can_estimate_periodicity")),
        }
    )
    return data, state


def build_gate(
    replay_memory: str = "v4_replay_memory.json",
    replay_analysis: str = "v4_replay_analysis.json",
    benchmark: str = "v4_baseline_benchmark.json",
    diversity: str = "v4_diversity_output.json",
    candidate_pool: str = "v4_candidate_pool_audit.json",
    physics: str = "v4_physics_regime_analysis.json",
) -> dict[str, Any]:
    replay_data, replay_state = _replay_input(replay_memory)
    replay_analysis_data, replay_analysis_state = _load_optional(replay_analysis)
    benchmark_data, benchmark_state = _benchmark_input(benchmark)
    diversity_data, diversity_state = _diversity_input(diversity)
    candidate_data, candidate_state = _candidate_pool_input(candidate_pool)
    physics_data, physics_state = _physics_input(physics)

    records = int(replay_state.get("records_replay") or 0)
    leakage = int(replay_state.get("leakage_passed_count") or 0)
    prior_quality = replay_state.get("prior_quality")
    ranking_quality = replay_state.get("ranking_signal_quality")
    benchmark_quality = benchmark_state.get("signal_quality")
    benchmark_recommendation = benchmark_state.get("recommendation")
    diversity_gain = float(diversity_state.get("diversity_gain") or 0.0)
    can_improve_pool = bool(candidate_state.get("can_improve_diversity_with_existing_data"))
    physics_suspected = bool(physics_state.get("latest_event_suspected"))
    physics_periodicity = bool(physics_state.get("can_estimate_periodicity"))

    gates = {
        "enough_records": replay_state.get("available") is True and records >= 30,
        "leakage_clean": records > 0 and leakage == records,
        "ranking_quality_ok": prior_quality == "usable_shadow" and ranking_quality in {"moderate", "strong"},
        "benchmark_ok": benchmark_state.get("available") is True and benchmark_quality in {"moderate", "strong"} and benchmark_recommendation == "diagnostic_only",
        "diversity_ok": diversity_state.get("available") is True and diversity_gain > 0 and can_improve_pool,
        "physics_regime_ok": physics_state.get("available") is True and (not physics_suspected or physics_periodicity),
    }
    can_influence = all(gates.values())
    required = []
    if not gates["ranking_quality_ok"]:
        required.append("ranking_signal_quality >= moderate")
        required.append("prior_quality = usable_shadow")
    if not gates["benchmark_ok"]:
        required.append("benchmark favorable vs random/frequency/recency")
    if not gates["diversity_ok"]:
        required.append("candidate pool broad enough for meaningful diversity")
    if not gates["physics_regime_ok"]:
        required.append("physical regime stable or segmented")
    if not gates["enough_records"]:
        required.append("at least 30 clean replay records")
    if not gates["leakage_clean"]:
        required.append("all replay records must pass leakage checks")

    if can_influence:
        reason = "All diagnostic gates passed; eligible only for a future explicit experiment."
    else:
        reason = "Replay remains blocked because one or more evidence gates are not satisfied."

    return {
        "version": VERSION,
        "generated_at": _utc_now(),
        "inputs": {
            "replay_memory": replay_state,
            "replay_analysis": replay_analysis_state,
            "benchmark": benchmark_state,
            "diversity": diversity_state,
            "candidate_pool": candidate_state,
            "physics": physics_state,
        },
        "gates": gates,
        "can_influence_future_prior": bool(can_influence),
        "eligible_for_future_experiment": bool(can_influence),
        "recommendation": "diagnostic_only",
        "reason": reason,
        "required_next_evidence": required,
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Build replay qualification gate.")
    parser.add_argument("--output", default="v4_replay_qualification.json")
    parser.add_argument("--replay-memory", default="v4_replay_memory.json")
    parser.add_argument("--replay-analysis", default="v4_replay_analysis.json")
    parser.add_argument("--benchmark", default="v4_baseline_benchmark.json")
    parser.add_argument("--diversity", default="v4_diversity_output.json")
    parser.add_argument("--candidate-pool", default="v4_candidate_pool_audit.json")
    parser.add_argument("--physics", default="v4_physics_regime_analysis.json")
    args = parser.parse_args()
    report = build_gate(
        replay_memory=args.replay_memory,
        replay_analysis=args.replay_analysis,
        benchmark=args.benchmark,
        diversity=args.diversity,
        candidate_pool=args.candidate_pool,
        physics=args.physics,
    )
    Path(args.output).write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Wrote {args.output}; can influence future prior: {report['can_influence_future_prior']}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
